# render.yaml
# This file defines the services to deploy on Render.

services:
  # Frontend Static Site
  - type: static # Corrected type from static_site to static
    name: speed-test-frontend
    buildCommand: # No build command needed for plain HTML/CSS/JS
    staticPublishPath: . # Publish everything in the root directory
    pullRequestPreviewsEnabled: true # Enable previews for pull requests
    envVars:
      - key: DISABLE_SPINNING_BUILD_ICON
        value: "true"

  # Backend Web Service
  - type: web
    name: speed-test-backend
    env: python # Specify Python environment
    buildCommand: "pip install -r backend/requirements.txt" # Install Python dependencies
    startCommand: "gunicorn app:app" # Command to start the Flask app using Gunicorn
    rootDir: backend/ # The root directory for this service within the repository
    healthCheckPath: / # Optional: A path that Render can hit to check if the service is healthy
    pullRequestPreviewsEnabled: true # Enable previews for pull requests
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.19 # Specify Python version for consistency
